export const CATEGORIES = [
  'Accrobranche',
  'Arène',
  'Bibliothèque',
  'Bowling',
  'Centre aquatique',
  'Centre commercial',
  'Centre culturel',
  'Centre de sciences',
  'Château',
  'Cinéma',
  'Église',
  'Escape game',
  'Ferme',
  'Hippodrome',
  'Jardin',
  'Jardin botanique',
  'Karting',
  'Lac',
  'Laser game',
  'Librairie',
  'Marché',
  'Mini golf',
  'Musée',
  'Opéra',
  'Parc',
  "Parc d'attractions",
  'Parc de loisirs',
  'Parc de trampolines',
  'Patinoire',
  'Piscine',
  'Place',
  'Quartier',
  'Site historique',
  'Théâtre',
  'Zoo',
];

export const PRICE_RANGES = ['Gratuit', '€', '€€', '€€€'];
